const types = {
    START_FETCH_DATA: 'START_FETCH_DATA',
    FINISH_FETCH_DATA: 'FINISH_FETCH_DATA',
    HANDLE_ERROR: 'HANDLE_ERROR',
    SET_BUTTONS_SIZE: 'SET_BUTTONS_SIZE',
    SET_BUTTONS_OUTLINE: 'SET_BUTTONS_OUTLINE',
    SET_CANCEL_TOKEN: 'SET_CANCEL_TOKEN'
}

export default types;